### ISSUE TITLE
Problems with Maven resolving

### ISSUE THREAD

**Issue by dmg46664** [scaled/pacman#4]
So Scaled got me to finally fall completely down the Emacs, rabbit hole. 😄 

Of course I still have the JVM itch, so after a long hiatus decided to reinstall.

```
$ spam install scaled
-- Cloning git:https://github.com/scaled/scaled.git into temp dir...
-- Updating git:https://github.com/scaled/pacman.git...
Already up to date.
-- Building scaled...
Building scaled#std...
MavenResolver.transferFailed GET FAILED http://central.maven.org/maven2/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom <> /Users/dmg46664/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom
MavenResolver.transferFailed GET FAILED http://repo.gradle.org/gradle/libs-releases-local/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom <> /Users/dmg46664/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.pom
src/scala/scaled/Mutable.scala:7: error: object google is not a member of package com
import com.google.common.cache.{LoadingCache, CacheBuilder, CacheLoader}
           ^
src/scala/scaled/Mutable.scala:14: error: not found: type LoadingCache
  def cacheMap[K,V] (filler :K => V) :LoadingCache[K,V] =
                                      ^
src/scala/scaled/Mutable.scala:15: error: not found: value CacheBuilder
    CacheBuilder.newBuilder().asInstanceOf[CacheBuilder[Any,Any]].build(new CacheLoader[K,V]() {
    ^
src/scala/scaled/Mutable.scala:15: error: not found: type CacheBuilder
    CacheBuilder.newBuilder().asInstanceOf[CacheBuilder[Any,Any]].build(new CacheLoader[K,V]() {
                                           ^
src/scala/scaled/Mutable.scala:15: error: not found: type CacheLoader
    CacheBuilder.newBuilder().asInstanceOf[CacheBuilder[Any,Any]].build(new CacheLoader[K,V]() {
                                                                            ^
5 errors found
Install failed
java.io.IOException: Scala build failed.
	at scaled.pacman.Exec$Handle.expect(Exec.java:28)
	at scaled.pacman.PackageBuilder.buildScala(PackageBuilder.java:113)
	at scaled.pacman.PackageBuilder.build(PackageBuilder.java:73)
	at scaled.pacman.PackageBuilder.build(PackageBuilder.java:40)
	at scaled.pacman.PackageOp.install(PackageOp.java:38)
	at scaled.pacman.Pacman.install(Pacman.java:153)
	at scaled.pacman.Pacman.install(Pacman.java:138)
	at scaled.pacman.Pacman.main(Pacman.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scaled.pacman.Bootstrap.main(Bootstrap.java:107)
```

Maven is reporting

```
Error 403 Use https://repo1.maven.org
Use https://repo1.maven.org

Guru Mediation:
Details: cache-lon4263-LON 1580082112 1090494035

Varnish cache server
```

I don't believe it's the same issue as https://github.com/samskivert/mfetcher/issues/1 because `mvn test` is passing (which seems strange if Maven has changed). I guess something has either changed for me or for maven. Either way hacking my `MavenResolver.java` file adding `repo1.maven.org` got me passed the issue, but I'm not sure this is the right way to go about it.

Nothing urgent, but I thought I'd flag it for others.

**Comment by samskivert** [comment]
Thanks! I went ahead and updated mfetcher to use repo1 and https, which will hopefully keep things working with Maven Central.

**Comment by samskivert** [comment]
Also just as context for your renewed forays into Scaled territory, I'm still using it full time and have  been slowly evolving it to work better with compilers that support LSP (dotc falls nicely into this category, scalac less so, though I periodically beat my head against SBT and Metal and the other things in the ecosystem that aim to make this work better).

I'll probably actually migrate all the Scaled code to Dotty at some point, just for fun, but I'm not in a rush. The main motivation is that once I've done that, I can retire a bunch of my hacky hand-made code for providing code intelligence when working on Scala and Java code and revamp Scaled to use LSP "out of the box" when editing Scaled code. It already uses LSP out of the box in some situations, but not on itself.

Anhow, just some FYI, if you have any questions during this new foray feel free to send them to the Scaled mailing list. I still use it as my main IDE every day (working in a variety of languages), though it still probably has an active user base of one. :)

**Comment by dmg46664** [comment]
* Looks up `Dotty`.
Oooh.
